# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f4426337370284da7d1ef7f43c75ce0e4a765df281f0411c9a4fa4b56c6078455736e40e60e2dc0bfe02b962bf5c0bb77b0dc3fceb66ef85f95fff3cda2c4c8

test:
  secret_key_base: a870810ad482a059d98b15c1ead185f93f4430f9b5a9cf96bba1f6018f0f3d44d2c9168406110fdc6375fc7e99000d36a98418c171f470ad43eb114aac7fedc6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
